export class ListCategory {
  static categogy: string[] = [
    'Không rõ',
    'Kỷ niệm',
    'Video games',
    'Anime',
    'Gái xinh',
    'Màu sắc',
    'Heros',
    'Trẻ em',
    'Jav Idol',
    'Đàn ông',
    'Phụ nữ',
    'Trừu tượng',
    'Animals',
    'Thức uống',
    'Giải trí',
    'Đồ ăn',
    'Lễ hội',
    'Thiên nhiên ',
    'Con người',
    'Thể thao',
    'Công nghệ',
    'Thế giới',
    '3D',
    'Dark',
    'Fantasy',
    'Fractal',
    'Texts',
    'Texture',
    'Vector',
  ];
}
